# -*- coding: utf-8 -*-
"""actividad8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iojmyNHvXLWAPN5LscPjofljUgYgu85X
"""

tareas = ["Comprar leche", "Estudiar Python", "Hacer ejercicio"]
with open("tareas.txt", "w") as archivo:
    for tarea in tareas:
        archivo.write(tarea + "\n")
with open("tareas.txt", "r") as archivo:
    lineas = archivo.readlines()
    for linea in lineas:
        print(linea.strip())

nueva_tarea = input("Introduce una nueva tarea: ")
with open("tareas.txt", "a") as archivo:
    archivo.write(nueva_tarea + "\n")