# -*- coding: utf-8 -*-
"""actividad1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iojmyNHvXLWAPN5LscPjofljUgYgu85X
"""

print("¡HOLA, MUNDOOO!")