# -*- coding: utf-8 -*-
"""actividad7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iojmyNHvXLWAPN5LscPjofljUgYgu85X
"""

matematicas/

 __init__.py
 modulo1.py
 modulo2.py

 from matematicas import modulo1
 def area_basica(suma1, suma2):
return suma1 + suma 2
def area_avanzada(radio):
import math
return math.pi * radio * radio
from calculos import area_rectangulo, area_circulo
print(area_rectangulo(10, 2))
print(area_circulo(5))