# -*- coding: utf-8 -*-
"""actividad4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iojmyNHvXLWAPN5LscPjofljUgYgu85X
"""

def celsius_a_fahrenheit(celsius):
    # The return statement needs to be indented to be part of the function body
    return (celsius * 9/5) + 32
grados_c = 25
print(celsius_a_fahrenheit(grados_c))